# Generated by Django 5.0.6 on 2024-05-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("STD", "STANDART"),
                            ("BDR", "BEDROOM"),
                            ("SPR", "SUPERIOR"),
                            ("STD", "STUDIO"),
                            ("DLX", "DELUXE"),
                        ],
                        max_length=3,
                    ),
                ),
                ("count_beds", models.IntegerField()),
                ("capacity", models.IntegerField()),
            ],
        ),
    ]
