# Generated by Django 5.0.6 on 2024-06-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Hotel", "0002_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="type",
            field=models.CharField(
                choices=[
                    ("STD", "STANDART"),
                    ("BDR", "BEDROOM"),
                    ("SPR", "SUPERIOR"),
                    ("DLX", "DELUXE"),
                ],
                max_length=3,
            ),
        ),
    ]
