# Generated by Django 5.0.6 on 2024-06-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Hotel", "0003_alter_apartment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="desription",
            field=models.CharField(default="", max_length=10000),
        ),
    ]
