# Generated by Django 5.0.6 on 2024-06-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Hotel", "0004_apartment_desription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="desription",
            field=models.CharField(
                choices=[
                    (
                        "STD",
                        "Уютный номер с односпальной кроватью, идеальный для одного человека.",
                    ),
                    (
                        "BDR",
                        "Просторный номер с двуспальной кроватью, идеальный для пары или семьи",
                    ),
                    (
                        "SPR",
                        "Номер с большой комнатой и кухней, идеальный для полного удобства одной семьи",
                    ),
                    (
                        "DLX",
                        "Самый продвинутый номер в гостинице, выход на балкон, минибар, несколько комнат, allinclusive, и прочее прочее.",
                    ),
                ],
                default="",
                max_length=10000,
            ),
        ),
    ]
