# Generated by Django 5.0.6 on 2024-06-24 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Hotel", "0005_alter_apartment_desription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="capacity",
        ),
    ]
